package errors

import (
	stdErrors "errors"
	"fmt"

	"github.com/hashicorp/go-multierror"
	"github.com/onflow/cadence/runtime"
	"github.com/onflow/cadence/runtime/errors"
)

type Unwrappable interface {
	Unwrap() error
}

type CodedError interface {
	Code() ErrorCode

	Unwrappable
	error
}

// CodedFailure is a subtype of CodedError specifically for failures
// This is used to make type checking with `errors.As` and `errors.Is` easier and more accurate
type CodedFailure interface {
	CodedError
	IsFailure()
}

// WrappedParentError is a wrapper for errors.ParentError to make it conform to the unwrappable
// interface used by the std errors lib. Once these error types are updated, this can be removed.
// See https://github.com/onflow/cadence/issues/3035
type WrappedParentError struct {
	errors.ParentError
}

func (err WrappedParentError) Unwrap() []error {
	return err.ParentError.ChildErrors()
}

// Is is a utility function to call std error lib `Is` function for instance equality checks.
func Is(err error, target error) bool {
	return stdErrors.Is(err, target)
}

// As is a utility function to call std error lib `As` function.
// As finds the first error in err's chain that matches target,
// and if so, sets target to that error value and returns true. Otherwise, it returns false.
// The chain consists of err itself followed by the sequence of errors obtained by repeatedly calling Unwrap.
func As(err error, target interface{}) bool {
	return stdErrors.As(err, target)
}

// findImportantCodedError recursively unwraps the error to search for important
// coded error:
//  1. If err is nil, this returns (nil, false),
//  2. If err has no error code, this returns (nil, true),
//  3. If err has a failure error code, this returns
//     (<the shallowest failure coded error>, false),
//  4. If err has a non-failure error code, this returns
//     (<the deepest, aka root cause, non-failure coded error>, false)
func findImportantCodedError(err error) (CodedError, bool) {
	if err == nil {
		return nil, false
	}

	var coded CodedError
	if !As(err, &coded) {
		return nil, true
	}

	for {
		if coded.Code().IsFailure() {
			return coded, false
		}

		var nextCoded CodedError
		if !As(coded.Unwrap(), &nextCoded) {
			return coded, false
		}

		coded = nextCoded
	}
}

// IsFailure returns true if the error is un-coded, or if the error contains
// a failure code.
func IsFailure(err error) bool {
	if err == nil {
		return false
	}

	coded, isUnknown := findImportantCodedError(err)
	return isUnknown || coded.Code().IsFailure()
}

// SplitErrorTypes splits the error into fatal (failures) and non-fatal errors
func SplitErrorTypes(inp error) (err CodedError, failure CodedError) {
	if inp == nil {
		return nil, nil
	}

	coded, isUnknown := findImportantCodedError(inp)
	if isUnknown {
		return nil, NewUnknownFailure(inp)
	}

	if coded.Code().IsFailure() {
		return nil, WrapCodedFailure(
			coded.Code(),
			inp,
			"failure caused by")
	}

	return WrapCodedError(
		coded.Code(),
		inp,
		"error caused by"), nil
}

// HandleRuntimeError handles runtime errors and separates
// errors generated by runtime from fvm errors (e.g. environment errors)
func HandleRuntimeError(inp error) (err error) {
	if inp == nil {
		return nil
	}

	// if is not a runtime error return as vm error
	// this should never happen unless a bug in the code
	runErr, ok := inp.(runtime.Error)
	if !ok {
		return NewUnknownFailure(err)
	}

	// wrap all runtime errors as CadenceRuntimeError
	defer func() {
		err = WrapCodedError(
			ErrCodeCadenceRunTimeError,
			err,
			"cadence runtime error",
		)
	}()

	// cadence ParentError types contain a list of errors encountered during execution
	// these need to be handled carefully because the std errors lib and the logic in this file
	// behave subtly different wrt which errors are returned. specifically:
	// - std errors methods will recursively unwrap single errors and error lists until they finds
	//   the first match using a depth-first search.
	// - findImportantCodedError will also recursively unwrap single errors and error lists, but it
	//   will continue to search until it finds the deepest coded error in the first branch containing
	//   any coded error. This means it will fail to find CodedFailures if there are any CodedErrors
	//   earlier in the unwrapped error list.
	var parentErr errors.ParentError
	if As(inp, &parentErr) {
		// wrap ParentErrors so they conform to unwrappable interface
		wrapped := WrappedParentError{parentErr}

		// first search through all of the errors for a coded failure. this ensures that a failure
		// is returned if there were any failures anywhere in the error tree.
		var failure CodedFailure
		if As(wrapped, &failure) {
			err = WrapCodedFailure(
				failure.Code(),
				inp,
				"cadence runtime failure caused by",
			)
			return
		}

		// next, do a depth-first search for the first coded error. this ensures that the deepest
		// coded error in the chain is returned.
		var coded CodedError
		if As(wrapped, &coded) {
			// find the deepest coded error
			coded, _ = findImportantCodedError(coded)
			// we've already check that the error is a CodedError, so ignoring the return value
			err = WrapCodedError(
				coded.Code(),
				inp,
				"cadence runtime error caused by",
			)
			return
		}
	}

	// All other errors are non-fatal Cadence errors.
	err = runErr
	return
}

// This returns true if the error or one of its nested errors matches the
// specified error code.
func HasErrorCode(err error, code ErrorCode) bool {
	return Find(err, code) != nil
}

// This recursively unwraps the error and returns first CodedError that matches
// the specified error code.
func Find(originalErr error, code ErrorCode) CodedError {
	if originalErr == nil {
		return nil
	}

	var unwrappable Unwrappable
	if !As(originalErr, &unwrappable) {
		return nil
	}

	coded, ok := unwrappable.(CodedError)
	if ok && coded.Code() == code {
		return coded
	}

	// NOTE: we need to special case multierror.Error since As() will only
	// inspect the first error within multierror.Error.
	errors, ok := unwrappable.(*multierror.Error)
	if !ok {
		return Find(unwrappable.Unwrap(), code)
	}

	for _, innerErr := range errors.Errors {
		coded = Find(innerErr, code)
		if coded != nil {
			return coded
		}
	}

	return nil
}

type codedError struct {
	code ErrorCode

	err error
}

func newError(
	code ErrorCode,
	rootCause error,
) codedError {
	return codedError{
		code: code,
		err:  rootCause,
	}
}

func WrapCodedError(
	code ErrorCode,
	err error,
	prefixMsgFormat string,
	formatArguments ...interface{},
) codedError {
	if code.IsFailure() {
		panic(fmt.Sprintf("cannot wrap failure (%s) as CodedError", code))
	}
	if prefixMsgFormat != "" {
		msg := fmt.Sprintf(prefixMsgFormat, formatArguments...)
		err = fmt.Errorf("%s: %w", msg, err)
	}
	return newError(code, err)
}

func NewCodedError(
	code ErrorCode,
	format string,
	formatArguments ...interface{},
) codedError {
	if code.IsFailure() {
		panic(fmt.Sprintf("cannot wrap failure (%s) as CodedError", code))
	}
	return newError(code, fmt.Errorf(format, formatArguments...))
}

func (err codedError) Unwrap() error {
	return err.err
}

func (err codedError) Error() string {
	return fmt.Sprintf("%v %v", err.code, err.err)
}

func (err codedError) Code() ErrorCode {
	return err.code
}

// codedFailure is a subtype of CodedError specifically for failures
type codedFailure struct {
	CodedError
}

func newFailure(
	code ErrorCode,
	rootCause error,
) codedFailure {
	return codedFailure{
		CodedError: newError(code, rootCause),
	}
}

func WrapCodedFailure(
	code ErrorCode,
	err error,
	prefixMsgFormat string,
	formatArguments ...interface{},
) codedFailure {
	if !code.IsFailure() {
		panic(fmt.Sprintf("cannot wrap non-failure (%s) as CodedFailure", code))
	}
	if prefixMsgFormat != "" {
		msg := fmt.Sprintf(prefixMsgFormat, formatArguments...)
		err = fmt.Errorf("%s: %w", msg, err)
	}
	return newFailure(code, err)
}

func NewCodedFailure(
	code ErrorCode,
	format string,
	formatArguments ...interface{},
) codedFailure {
	if !code.IsFailure() {
		panic(fmt.Sprintf("cannot wrap non-failure (%s) as CodedFailure", code))
	}
	return newFailure(code, fmt.Errorf(format, formatArguments...))
}

func (err codedFailure) IsFailure() {}

// NewEventEncodingError construct a new CodedError which indicates
// that encoding event has failed
func NewEventEncodingError(err error) CodedError {
	return NewCodedError(
		ErrCodeEventEncodingError,
		"error while encoding emitted event: %w ", err)
}

// EVMError needs to satisfy the user error interface
// in order for Cadence to correctly handle the error
var _ errors.UserError = &(EVMError{})

type EVMError struct {
	CodedError
}

func (e EVMError) IsUserError() {}

// NewEVMError constructs a new CodedError which captures a
// collection of errors provided by (non-fatal) evm runtime.
func NewEVMError(err error) EVMError {
	return EVMError{
		WrapCodedError(
			ErrEVMExecutionError,
			err,
			"evm runtime error"),
	}
}

// IsEVMError returns true if error is an EVM error
func IsEVMError(err error) bool {
	return HasErrorCode(err, ErrEVMExecutionError)
}
